Network byte count
multiversx/mx-chain-vm-go pull request #635
Opened 2022-10-19 09:15 UTC by matei-p

2022-10-19 11:03 UTC, andrei-marinica approved these changes

2022-10-19 13:16 UTC, camilbancioiu requested changes

2022-10-19 13:47 UTC, matei-p commented on arwen/contexts/output.go
> +		account.BytesConsumedByTxAsNetworking += uint64(len(transfer.Data))
good ideea

2022-10-19 13:56 UTC, camilbancioiu approved these changes

2022-11-10 08:02 UTC, andrei-marinica approved these changes

2022-11-10 08:03 UTC, sasurobert submitted a review, later dismissed

2023-02-09 12:41 UTC, sasurobert approved these changes

2023-02-09 14:05 UTC, camilbancioiu approved these changes

2023-02-09 14:06 UTC, merged