Fix Wasmer executor switching (sighandler reinstallation)
multiversx/mx-chain-vm-go pull request #728
Opened 2023-03-15 13:23 UTC by camilbancioiu

This PR changes how Wasmer executors and bridges are initialized and adds calls to new functions in the Wasmer binaries, in order to reinstall the corresponding signal handlers.

This PR also updates the binaries for Wasmer 1 and for the Wasmer 2 executor, containing required changes.

2023-03-16 15:15 UTC, sasurobert submitted a review, later dismissed

2023-03-16 15:39 UTC, ovstinga approved these changes

2023-03-17 08:40 UTC, sasurobert requested changes
Integration is not working on all machines.

2023-03-17 09:18 UTC, sasurobert approved these changes

2023-03-17 09:19 UTC, ovstinga approved these changes

2023-03-17 09:20 UTC, merged