mockESDT missing account error handling
multiversx/mx-chain-vm-go pull request #757
Opened 2023-08-10 07:59 UTC by andrei-marinica

2023-08-10 08:03 UTC, CostinCarabas approved these changes

2023-08-10 08:04 UTC, sasurobert requested changes

2023-08-10 08:04 UTC, sasurobert commented on mock/world/mockESDT.go
> +	if account == nil {
check.ifNil

2023-08-10 08:08 UTC, alyn509 submitted a review, later dismissed

2023-08-10 08:08 UTC, sasurobert approved these changes

2023-08-10 08:10 UTC, sasurobert requested changes
this is not how the real VM works.

2023-08-10 16:04 UTC, CostinCarabas approved these changes

2023-08-11 07:12 UTC, alyn509 approved these changes

2023-08-11 07:16 UTC, sasurobert approved these changes

2023-08-11 07:20 UTC, merged