IsBuiltinFunctionName vmhook impl
multiversx/mx-chain-vm-go pull request #851
Opened 2024-06-07 09:45 UTC by laurci

2024-06-07 13:53 UTC, sasurobert requested changes

2024-06-07 13:53 UTC, sasurobert commented on vmhost/vmhooks/baseOps.go
> +	name, err := context.MemLoad(nameOffset, nameLength)
missing useGas.

2024-06-07 13:53 UTC, sasurobert commented on vmhost/vmhooks/baseOps.go
> +	if host.IsBuiltinFunctionName(string(name)) {
// IsReserved returns whether a function is reserved
func (reservedFunctions *reservedFunctions) IsReserved(functionName string) bool { 

It is much better to call this. And rename the hook to IsReservedName

2024-06-13 08:07 UTC, sasurobert submitted a review, later dismissed

2024-06-13 11:16 UTC, sasurobert approved these changes

2024-06-13 11:23 UTC, andrei-marinica approved these changes

2024-06-13 11:33 UTC, merged