With fault refactor
multiversx/mx-chain-vm-go pull request #873
Opened 2024-08-22 10:37 UTC by sasurobert

2024-08-22 15:04 UTC, andrei-marinica requested changes

2024-08-22 15:08 UTC, sasurobert commented on vmhost/vmhooks/baseOps.go
> +	if err != nil && runtime.UseGasBoundedShouldFailExecution() {
yes- it is needed because of backward compatibility issues.

2024-08-22 15:09 UTC, sasurobert commented on vmhost/vmhooks/bigFloatOps.go
> +	if err != nil {
deleted.

2024-08-22 15:10 UTC, andrei-marinica approved these changes

2024-08-23 07:50 UTC, laurci approved these changes

2024-08-30 16:59 UTC, merged